app/problem/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms.fields import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, ValidationError

class NewProblemField(FlaskForm):
    title = StringField('Title', [DataRequired()])
    abbr = StringField('Abbr.', [DataRequired()])
    submit = SubmitField('Create')

    def validate_submit(self, field):
        if current_user.id != 1:
            raise ValidationError('Forbidden!')

class ProblemField(FlaskForm):
    title = StringField('Title', [DataRequired()])
    abbr = StringField('Abbr', [DataRequired()])
    content = TextAreaField('Content')
    scoring_script = TextAreaField('Scoring Script')
    submit = SubmitField('Update')

    def validate_submit(self, field):
        if current_user.id != 1:
            raise ValidationError('Forbidden!')

class TestDataField(FlaskForm):
    inputs = TextAreaField('Inputs')
    answers = TextAreaField('Outputs')
    time_limit = IntegerField('Time Limit (ms)')
    memory_limit = IntegerField('Memory Limit (KiB)')
    score = IntegerField('Score')
    submit = SubmitField('Save')

    def validate_submit(self, field):
        if current_user.id != 1:
            raise ValidationError('Forbidden!')

app/problem/__init__.py
from flask import Blueprint

problem = Blueprint('problem', __name__)

from . import views

app/problem/views.py
from flask import render_template, redirect, url_for
from flask_login import login_required, current_user
from datetime import datetime
from . import problem
from .forms import NewProblemField, ProblemField, TestDataField
from ..models import Problem, TestData
from .. import db

@problem.route('/problems', methods = ['GET', 'POST'])
@login_required
def problems():
    form = NewProblemField()
    if form.validate_on_submit():
        problem = Problem(abbr = form.abbr.data, title = form.title.data)
        db.session.add(problem)
        db.session.commit()
        return redirect(url_for('problem.show', pid = problem.id))
    problems = Problem.query.order_by(Problem.id).all()
    return render_template('problem/problems.html', current_time = datetime.utcnow(), form = form, problems = problems)

@problem.route('/problems/<pid>', methods = ['GET', 'POST'])
@login_required
def show(pid):
    form = ProblemField()
    problem = Problem.query.get_or_404(pid)
    if form.validate_on_submit():
        problem.abbr = form.abbr.data
        problem.title = form.title.data
        problem.content = form.content.data
        db.session.add(problem)
        db.session.commit()
        return redirect(url_for('problem.show', pid = pid))
    form.abbr.data = problem.abbr
    form.title.data = problem.title
    form.content.data = problem.content
    testdata = TestData.query.filter_by(pid = pid).all()
    return render_template('problem/show.html', current_time = datetime.utcnow(), form = form, problem = problem, testdata = testdata)

@problem.route('/problems/<pid>/new_testdata')
@login_required
def new_testdata(pid):
    testdata = TestData(pid = pid)
    db.session.add(testdata)
    db.session.commit()
    return redirect(url_for('problem.testdata', tid = testdata.id))

@problem.route('/problems/testdata/<tid>', methods = ['GET', 'POST'])
@login_required
def testdata(tid):
    form = TestDataField()
    testdata = TestData.query.get_or_404(tid)
    if form.validate_on_submit():
        testdata.score = form.score.data
        testdata.input = form.inputs.data
        testdata.answer = form.answers.data
        testdata.time_limit = form.time_limit.data
        testdata.memory_limit = form.memory_limit.data
        db.session.add(testdata)
        db.session.commit()

        problem = Problem.query.get_or_404(testdata.pid)
        testdatas = TestData.query.filter_by(pid = testdata.pid).all()
        problem.total_score = 0
        for data in testdatas:
            problem.total_score += data.score
        db.session.add(problem)
        db.session.commit()

        return redirect(url_for('problem.show', pid = testdata.pid))

    form.score.data = testdata.score
    form.inputs.data = testdata.input
    form.answers.data = testdata.answer
    form.time_limit.data = testdata.time_limit
    form.memory_limit.data = testdata.memory_limit
    return render_template('problem/testdata.html', current_time = datetime.utcnow(), form = form)

app/templates/problem/problems.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_title %}Problems{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-3">Problems</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col" style="width:70%;">Title</th>
                        <th scope="col">Score</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for problem in problems %}
                    <tr>
                        <th>{{ problem.abbr }}</th>
                        <td><a href="{{ url_for('problem.show', pid = problem.id) }}">{{ problem.title }}</a></td>
                        <td>{{ problem.total_score }}</td>
                        <td>-</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div><br>
    {% if current_user.id == 1 %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-3">New Problem</h4>
            <hr>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="row">
                    <div class="form-group col-sm-3">
                        {{ form.abbr.label }}{{ form.abbr(class='form-control') }}
                    </div>
                    <div class="form-group col-sm-9">
                        {{ form.title.label }}{{ form.title(class='form-control') }}
                    </div>
                </div>
                {{ form.submit(class='btn float-right') }}
            </form>
        </div>
    </div><br>
    {% endif %}
</div>
{% endblock %}

app/templates/problem/show.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_title %}{{ problem.abbr }}{% endblock %}

{% block scripts %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/tomorrow.min.css">
{{ super() }}
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/highlight.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        document.querySelectorAll('code').forEach((block) => {
            hljs.highlightBlock(block);
        });
    });
</script>
{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <div class="card">
        <div class="card-body content">
            <h4 class="card-title mb-3">{{ problem.title }}</h4>
            <hr>
            {{ problem.content_html | safe }}
            <hr>
            <div class="row">
                <div class="col-sm-4">Total Score:　{{ problem.total_score }}</div>
                <div class="col-sm-4"></div>
                <div class="col-sm-4"><a href="{{ url_for('submission.submit', pid = problem.id) }}"><button class="btn float-right">Submit
                            Solution</button></a></div>
            </div>
        </div>
    </div><br>
    {% if current_user.id == 1 %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-3">Manage</h4>
            <hr>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="row">
                    <div class="form-group col-sm-2">
                        {{ form.abbr.label }}{{ form.abbr(class='form-control') }}
                    </div>
                    <div class="form-group col-sm-10">
                        {{ form.title.label }}{{ form.title(class='form-control') }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.content.label }}{{ form.content(class='form-control', style='height: 500px;') }}
                </div>
                {{ form.submit(class='btn float-right') }}
            </form>
        </div>
    </div><br>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-3">Test Data</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Time Limit</th>
                        <th scope="col">Memory Limit</th>
                        <th scope="col">Score</th>
                        <th scope="col">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in testdata %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ data.time_limit }}</td>
                        <td>{{ data.memory_limit }}</td>
                        <td>{{ data.score }}</td>
                        <td><a href="{{ url_for('problem.testdata', tid = data.id) }}">Manage</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr>
            <a href="{{ url_for('problem.new_testdata', pid = problem.id) }}"><button class="btn float-right">Add</button></a>
        </div>
    </div><br>

    {% endif %}
</div>
{% endblock %}

app/templates/problem/testdata.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_title %}Test Data{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <div class="card">
        <div class="card-body content">
            <h4 class="card-title mb-3">Test Data</h4>
            <hr>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="row">
                    <div class="form-group col-sm-4">
                        {{ form.score.label }}{{ form.score(class='form-control') }}
                    </div>
                    <div class="form-group col-sm-4">
                        {{ form.time_limit.label }}{{ form.time_limit(class='form-control') }}
                    </div>
                    <div class="form-group col-sm-4">
                        {{ form.memory_limit.label }}{{ form.memory_limit(class='form-control') }}
                    </div>
                </div>
                <div class="form-group">{{ form.inputs.label }}{{ form.inputs(class = 'form-control', style = 'height:
                    100px;') }}</div>
                <div class="form-group">{{ form.answers.label }}{{ form.answers(class = 'form-control', style =
                    'height: 100px;') }}</div>
                {{ form.submit(class = 'btn float-right') }}
            </form>
        </div>
    </div><br>
</div>
{% endblock %}