app/submission/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField, SubmitField
from wtforms.validators import DataRequired, NumberRange

class SubmitForm(FlaskForm):
    code = TextAreaField('Code')
    submit = SubmitField('Submit')

app/submission/__init__.py
from flask import Blueprint

submission = Blueprint('submission', __name__)

from . import views

app/submission/views.py
from flask import render_template, request, redirect, url_for, current_app
from flask_login import login_required, current_user
from datetime import datetime
from hashlib import md5
from .forms import SubmitForm
from . import submission
from .. import db
from ..models import Submission, User, Problem, TestData

@submission.route('/submissions')
def list():
    page = request.args.get('page', 1, type=int)
    pagination = Submission.query.order_by(Submission.id.desc()).paginate(page, per_page = current_app.config['ITEMS_PER_PAGE'], error_out=True)
    submissions = pagination.items
    problems = Problem
    user = User
    return render_template('submissions/list.html', current_time = datetime.utcnow(), submissions = submissions, pagination = pagination, user = user, problems = problems)

@submission.route('/<uid>/submissions')
def list_by_user(uid):
    page = request.args.get('page', 1, type=int)
    pagination = Submission.query.order_by(Submission.id.desc()).filter_by(uid = uid).paginate(page, per_page = current_app.config['ITEMS_PER_PAGE'], error_out = True)
    submissions = pagination.items
    problems = Problem
    user = User.query.get_or_404(uid)
    return render_template('submissions/list_by_user.html', current_time = datetime.utcnow(), submissions = submissions, pagination = pagination, user = user, problems = problems)

@submission.route('/submissions/<sid>')
def result(sid):
    submission = Submission.query.get_or_404(sid)
    problem = Problem.query.get(submission.pid)
    testdata = TestData.query.filter_by(pid = submission.pid)
    user = User.query.get(submission.uid)

    return render_template('submissions/result.html', current_time = datetime.utcnow(), submission = submission, user = user, problem = problem, testdata = testdata)

@submission.route('/problems/<pid>/submit', methods = ['GET', 'POST'])
@login_required
def submit(pid):
    form = SubmitForm()
    if form.validate_on_submit():
        submission = Submission(pid = pid, uid = current_user.id, code = form.code.data, create_time = datetime.utcnow(), verdict = 'Pending')
        db.session.add(submission)
        db.session.commit()
        
        return redirect(url_for('submission.result', sid = submission.id))
    problem = Problem.query.get_or_404(pid)
    return render_template('submissions/submit.html', current_time = datetime.utcnow(), form = form, pid = pid, problem = problem)

app/templates/submissions/list.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_title %}Submissions{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-3">Submissions</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Problem</th>
                        <th scope="col">Submitter</th>
                        <th scope="col">Time</th>
                        <th scope="col">Memory</th>
                        <th scope="col">Verdict</th>
                        <th scope="col">Score</th>
                        <th scope="col">Submit Time</th>
                    </tr>
                <tbody>
                    {% for submission in submissions %}
                    <tr class="table-default">
                        <th scope="row"><a href="{{ url_for('submission.result', sid = submission.id) }}">{{
                                submission.id }}</a></th>
                        <td><a href="{{ url_for('problem.show', pid = submission.pid) }}">{{ problems.query.get(submission.pid).title }}</a></td>
                        <td><a href="{{ url_for('submission.list_by_user', uid = submission.uid) }}">{{ user.query.get(submission.uid).username }}</a></td>
                        <td>{{ submission.time or '-' }}</td>
                        <td>{{ submission.memory or '-' }}</td>
                        <td>{{ submission.verdict }}</td>
                        <td>{{ submission.score or '-' }}</td>
                        <td>{{ moment(submission.create_time).format('LTS') }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div><br>
    <div>
        {{ macros.pagination_widget(pagination, '.list') }}
    </div>
</div>
{% endblock %}

app/templates/submissions/list_by_user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_title %}Submissions{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-3">{{ user.username }}'s Submissions</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Problem</th>
                        <th scope="col">Submitter</th>
                        <th scope="col">Time</th>
                        <th scope="col">Memory</th>
                        <th scope="col">Verdict</th>
                        <th scope="col">Score</th>
                        <th scope="col">Submit Time</th>
                    </tr>
                <tbody>
                    {% for submission in submissions %}
                    <tr class="table-default">
                        <th scope="row"><a href="{{ url_for('submission.result', sid = submission.id) }}">{{
                                submission.id }}</a></th>
                        <td><a href="{{ url_for('problem.show', pid = submission.id) }}">{{ problems.query.get(submission.pid).title }}</a></td>
                        <td><a href="{{ url_for('submission.list_by_user', uid = user.id) }}">{{ user.username }}</a></td>
                        <td>{{ submission.time or '-' }}</td>
                        <td>{{ submission.memory or '-' }}</td>
                        <td>{{ submission.verdict }}</td>
                        <td>{{ submission.score or '-' }}</td>
                        <td>{{ moment(submission.create_time).format('LTS') }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div><br>
    <div>
        {{ macros.pagination_widget(pagination, '.list_by_user', uid = current_user.id) }}
    </div>
</div>
{% endblock %}

app/templates/submissions/result.html
{% extends "base.html" %}

{% block scripts %}
{{ super() }}
<script src="/static/ace/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/tomorrow");
    editor.session.setMode("ace/mode/c_cpp");
</script>
{% endblock %}

{% block page_title %}Result{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title mb-3">Submission - #{{ submission.id }}</h4>
                    <hr>
                    <div class="row">
                        <label class="col-sm-4 col-form-label">Problem</label>
                        <label class="col-sm-8 col-form-label"><a href="#">{{ problem.title }}</a></label>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 col-form-label">Submitter</label>
                        <label class="col-sm-8 col-form-label"><a href="{{ url_for('submission.list_by_user', uid = submission.uid) }}">{{
                                user.username
                                }}</a></label>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 col-form-label">Submit Time</label>
                        <label class="col-sm-8 col-form-label">{{ moment(submission.create_time).format('LTS') }}</label>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 col-form-label">Verdict</label>
                        <label class="col-sm-8 col-form-label">{{ submission.verdict or '-' }}</label>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 col-form-label">Score</label>
                        <label class="col-sm-8 col-form-label">{{ submission.score or 0 }} / {{ problem.total_score }}</label>
                    </div>
                </div>
            </div><br>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title mb-3">Tasks</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Time</th>
                                <th scope="col">Memory</th>
                                <th scope="col">Result</th>
                                <th scope="col">Score</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in testdata %}
                            <tr>
                                <th scope="row">{{ loop.index }}</th>
                                <td>-</td>
                                <td>-</td>
                                <td>Pending</td>
                                <td>0 / {{ data.score }}</td>
                            </tr>
                            {% endfor %}
                    </table>
                </div>
            </div><br>
        </div>
    </div>

    {% if current_user.id == submission.uid or current_user.id == 1 %}
    <div class="card" style="height: 400px;">
        <div class="card-body">
            <pre>
                <div id = "editor">{{ submission.code | replace("<", "&lt;") | replace(">", "&gt;") | safe }}</div>
            </pre>
        </div>
    </div><br><br>
    {% endif %}
</div>
{% endblock %}

app/templates/submissions/submit.html
{% extends "base.html" %}

{% block scripts %}
{{ super() }}
<script src="/static/ace//ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/tomorrow");
    editor.session.setMode("ace/mode/c_cpp");

    document.getElementById('editor').style.fontSize = '13px';

    var input = $('textarea[name="code"]');
    input.val(editor.getSession().getValue());

    editor.getSession().on("change", function () {
        input.val(editor.getSession().getValue());
    });
</script>
{% endblock %}

{% block page_title %}Submit{% endblock %}

{% block page_content %}
<div class="container" style="width: 90%">
    <form method="POST">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-3"><a href="{{ url_for('problem.show', pid = problem.id) }}">{{ problem.title
                        }}</a></h4>
                <hr>
                {{ form.hidden_tag() }}
                <div class="row">
                    <div class="col-sm-4">Total Score:　{{ problem.total_score }}</div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4">{{ form.submit(class = 'btn float-right') }}</div>
                </div>
            </div>
        </div><br>
        <div class="card">
            <div class="card-body" style="height: 500px">
                <div id="editor"></div>
                {{ form.code(style='display: none;') }}
            </div>
        </div><br>
    </form>
</div>
{% endblock %}